ci:
  autofix_prs: false

default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ["--maxkb=512"]
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md"]
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: check-yaml
        args: ["--allow-multiple-documents"]
        files: "\\.ya?ml$"
      - id: check-json
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        files: "\\.ya?ml$"
        args: ["-c", ".yamllint.yaml"]
