# this file contains a few env variables that you have to manually set in portainer or replace before deploy with the actual text
# - ${DOCKER_DATA_BASEFOLDER}

services:
  hbbs:
    container_name: hbbs
    image: rustdesk/rustdesk-server:latest
    command: hbbs
    volumes:
      - ${DOCKER_DATA_BASEFOLDER}/RustDesk:/root
    network_mode: "host"

    depends_on:
      - hbbr
    restart: unless-stopped

  hbbr:
    container_name: hbbr
    image: rustdesk/rustdesk-server:latest
    command: hbbr
    volumes:
      - ${DOCKER_DATA_BASEFOLDER}/RustDesk:/root
    network_mode: "host"
    restart: unless-stopped
