version: "2.1"

# this file contains a few env variables that you have to manually set in portainer or replace before deploy with the actual text
# - ${DOCKER_DATA_BASEFOLDER}

services:
  homeassistant:
    container_name: homeassistant
    image: lscr.io/linuxserver/homeassistant:latest
    #documentation: TODO: add documentation link
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    volumes:
      - ${DOCKER_DATA_BASEFOLDER}/homeassistant/config:/config
      - /run/dbus:/run/dbus:ro #bluetooth?
    ports:
      - 8123:8123 #optional
    restart: unless-stopped