# Pi-hole Stack
# This stack provides a network-wide ad blocking solution using Pi-hole.
#
# Note: Both mapped and exposed ports are documented. The long-term plan is to reduce direct port exposure in favor of reverse proxying for internal services.
#
# Required environment variables:
# - DOCKER_DATA_BASEFOLDER: Base directory for persistent data
# - PASSWORD: Web interface password
#
# Optional configuration:
# - Uncomment DHCP ports if using Pi-hole as DHCP server
# - Uncomment capabilities if using DHCP or NTP

services:
  pihole:
    container_name: pihole
    hostname: pi.hole-docker
    image: pihole/pihole:latest
    ports:
      - 53:53/tcp      # DNS (TCP, external mapping)
      - 53:53/udp      # DNS (UDP, external mapping)
      # - 81:80/tcp    # Web interface (external mapping, recommended to use reverse proxy instead)
      # - 443:443/tcp  # HTTPS (self-signed cert, external mapping, recommended to use reverse proxy instead)
      # - 67:67/udp    # DHCP server (external mapping, optional)
    expose:
      - 80  # Web interface (internal, for reverse proxy or internal access)
      - 443  # HTTPS (self-signed cert, internal, for reverse proxy or internal access)
      - 53  # DNS (internal, for internal container communication)
      - 67  # DHCP (internal, for internal container communication)
    environment:
      TZ: Europe/Rome
      FTLCONF_webserver_api_password: ${PASSWORD}
      FTLCONF_dns_listeningMode: all
    volumes:
      - ${DOCKER_DATA_BASEFOLDER:-/opt/docker/data}/pihole/etc-pihole:/etc/pihole
      - ${DOCKER_DATA_BASEFOLDER:-/opt/docker/data}/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    # cap_add:
      # - NET_ADMIN    # Required for DHCP
      # - SYS_TIME     # Required for NTP
      # - SYS_NICE     # Optional, for better performance
    restart: unless-stopped
    networks:
      - pihole_network
      - npm_network

networks:
  pihole_network:
    name: pihole_network
    driver: bridge
  npm_network: # to expose container to NPM for reverse proxy
    name: npm_network
    driver: bridge
    external: true
