#public endpoints for agents
location /meshagents {
    proxy_pass $forward_scheme://$server:$port;
}

location /agent.ashx {
    proxy_pass $forward_scheme://$server:$port;

    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
}

location /control.ashx {
    proxy_pass $forward_scheme://$server:$port;

    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
}

location /meshrelay.ashx {
    proxy_pass $forward_scheme://$server:$port;

    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
}

#deploy
location = /install.ps1 {
    alias /data/deploy/install.ps1;
    default_type text/plain;
    add_header Cache-Control "no-store";
}

# Root location
location / {
    proxy_pass $forward_scheme://$server:$port;
    satisfy any;
    allow 192.168.0.0/16;
    allow 172.16.0.0/12;
    allow 10.0.0.0/8;
    allow 100.64.0.0/10;
    deny all;
    auth_request /tinyauth;
    error_page 401 = @tinyauth_login;
}
location /tinyauth {
    proxy_pass http://tinyauth:3000/api/auth/nginx;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Uri $request_uri;
}
location @tinyauth_login {
    return 302 http://tinyauth.alsd.duckdns.org/login?redirect_uri=$scheme://$host$request_uri;
}
