name: romm

volumes:
  mysql_data:
  romm_resources:
  romm_redis_data:

services:
  romm:
    image: rommapp/romm:latest
    container_name: romm
    restart: unless-stopped
    environment:
      DB_HOST: romm-db
      DB_NAME: ${ROMM_DB_NAME}
      DB_USER: ${ROMM_DB_USER}
      DB_PASSWD: ${ROMM_DB_PASSWORD}
      ROMM_AUTH_SECRET_KEY: ${ROMM_AUTH_SECRET_KEY}
      SCREENSCRAPER_USER: ${SCREENSCRAPER_USER}
      SCREENSCRAPER_PASSWORD: ${SCREENSCRAPER_PASSWORD}
      RETROACHIEVEMENTS_API_KEY: ${RETROACHIEVEMENTS_API_KEY}
      STEAMGRIDDB_API_KEY: ${STEAMGRIDDB_API_KEY}
      HASHEOUS_API_ENABLED: ${HASHEOUS_API_ENABLED:-true}
    volumes:
      - romm_resources:/romm/resources # Resources fetched from IGDB (covers, screenshots, etc.)
      - romm_redis_data:/redis-data # Cached data for background tasks
      # - ${DOCKER_MEDIA_BASEFOLDER:-/opt/docker/media}/romm_library:/romm/library # Your game library. Check https://docs.romm.app/latest/Getting-Started/Folder-Structure/ for more details.
      - ${LOCAL_RETROPIE_BASE:-/opt/docker/media/retropie}/roms:/romm/library/roms
      - ${LOCAL_RETROPIE_BASE:-/opt/docker/media/retropie}/BIOS:/romm/library/bios
      - ${DOCKER_DATA_BASEFOLDER:-/opt/docker/data}/romm/assets:/romm/assets # Uploaded saves, states, etc.
      - ${DOCKER_DATA_BASEFOLDER:-/opt/docker/data}/romm/config:/romm/config # (Optional) Path where config.yml is stored
    expose:
      - 8080 # Web UI (internal, for reverse proxy or internal access)
    depends_on:
      romm-db:
        condition: service_healthy
        restart: true
    networks:
      - romm_network
      - npm_network

  romm-db:
    image: mariadb:latest
    container_name: romm-db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${ROMM_DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${ROMM_DB_NAME}
      MARIADB_USER: ${ROMM_DB_USER}
      MARIADB_PASSWORD: ${ROMM_DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 30s
      start_interval: 10s
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - romm_network

networks:
  romm_network:
    name: romm_network
    driver: bridge
  npm_network:
    name: npm_network
    driver: bridge
    external: true
