version: "3.8"

services:
  homebox:
#   image: ghcr.io/hay-kot/homebox:latest
    image: ghcr.io/hay-kot/homebox:latest-rootless
    container_name: homebox
    restart: always
    environment:
    - HBOX_LOG_LEVEL=info
    - HBOX_LOG_FORMAT=text
    - HBOX_WEB_MAX_UPLOAD_SIZE=10
    - HBOX_OPTIONS_ALLOW_REGISTRATION=false

    volumes:
      - ${DOCKER_DATA_BASEFOLDER}/homebox:/data
    ports:
      - 3100:7745
    user: "1000:1000"
