# this file contains a few env variables that you have to manually set in portainer or replace before deploy with the actual text
# - ${DOCKER_DATA_BASEFOLDER}

services:
  homebox:
 #  image: ghcr.io/sysadminsmedia/homebox:latest
    image: ghcr.io/sysadminsmedia/homebox:latest-rootless
    container_name: homebox
    restart: always
    environment:
    - HBOX_LOG_LEVEL=info
    - HBOX_LOG_FORMAT=text
    - HBOX_WEB_MAX_UPLOAD_SIZE=10
    - HBOX_OPTIONS_ALLOW_REGISTRATION=false

    volumes:
      - ${DOCKER_DATA_BASEFOLDER}/homebox:/data
    ports:
      - 3100:7745
    user: "1000:1000"
