# this file contains a few env variables that you have to manually set in portainer or replace before deploy with the actual text
# - ${DOCKER_DATA_BASEFOLDER}
# - ${TELEGRAM_BOT_TOKEN}
# - ${TELEGRAM_CHAT_ID}

# - ${DYNU_DOMAIN}
# - ${DYNU_PASSWORD}
# - ${DYNU_USERNAME}

# - ${DYN6_DOMAIN}
# - ${DYN6_TOKEN}

# - ${DUCK_HOST}
# - ${DUCK_TOKEN}

# - ${CLOUDFLARE_DOMAIN}
# - ${CLOUDFLARE_DOMAIN_2}
# - ${CLOUDFLARE_TOKEN}
# - ${CLOUDFLARE_ZONE_ID}
# - ${CLOUDFLARE_ZONE_ID_2}

services:
  ddns-updater:
    #docs: https://github.com/qdm12/ddns-updater/tree/master/docs
    image: qmcgaw/ddns-updater
    container_name: ddns-updater
    #    network_mode: bridge
    dns:
      - 1.1.1.1
    ports:
      - 8001:8000/tcp
    volumes:
      - ${DOCKER_DATA_BASEFOLDER}/ddns-updater:/updater/data
    environment:
      - CONFIG=
        {"settings":[
        {"provider":"dynu",      "domain":"${DYNU_DOMAIN}",          "username":"${DYNU_USERNAME}","password":"${DYNU_PASSWORD}",                      "ip_version":"ipv4"},
        {"provider":"dynv6",     "domain":"${DYN6_DOMAIN}",          "token":"${DYN6_TOKEN}",                                                          "ip_version":"ipv4"},
        {"provider":"duckdns",   "domain":"${DUCK_HOST}",            "token":"${DUCK_TOKEN}",                                                          "ip_version":"ipv4"},
        {"provider":"cloudflare","domain":"${CLOUDFLARE_DOMAIN}",    "token":"${CLOUDFLARE_TOKEN}","ttl":600,"zone_identifier":"${CLOUDFLARE_ZONE_ID}","ip_version":"ipv4"},
        {"provider":"cloudflare","domain":"*.${CLOUDFLARE_DOMAIN}",  "token":"${CLOUDFLARE_TOKEN}","ttl":600,"zone_identifier":"${CLOUDFLARE_ZONE_ID}","ip_version":"ipv4"},
        {"provider":"cloudflare","domain":"${CLOUDFLARE_DOMAIN_2}",  "token":"${CLOUDFLARE_TOKEN}","ttl":600,"zone_identifier":"${CLOUDFLARE_ZONE_ID_2}","ip_version":"ipv4"},
        {"provider":"cloudflare","domain":"*.${CLOUDFLARE_DOMAIN_2}","token":"${CLOUDFLARE_TOKEN}","ttl":600,"zone_identifier":"${CLOUDFLARE_ZONE_ID_2}","ip_version":"ipv4"}

        ]}
      - PERIOD=60m
      - UPDATE_COOLDOWN_PERIOD=5m
      - TZ=Europe/Rome
      #      - PUBLICIP_FETCHERS=all
      #      - PUBLICIP_HTTP_PROVIDERS=all
      #      - PUBLICIPV4_HTTP_PROVIDERS=all
      - PUBLICIP_DNS_PROVIDERS=all
      - PUBLICIP_DNS_TIMEOUT=3s
      - HTTP_TIMEOUT=10s

      # Web UI
      - LISTENING_PORT=8000
      - ROOT_URL=/

      # Backup
      - BACKUP_PERIOD=0 # 0 to disable
      - BACKUP_DIRECTORY=/updater/data

      # Other
      - LOG_LEVEL=debug
      - LOG_CALLER=hidden
      - RESOLVER_ADDRESS=1.1.1.1:53
      - SHOUTRRR_ADDRESSES=telegram://${TELEGRAM_BOT_TOKEN}@telegram/?channels=${TELEGRAM_CHAT_ID}&parsemode=Markdown&preview=false

    labels:
      telegram-notifier.monitor: false # never monitor
    restart: always
