# Tools Stack
# This stack provides a collection of useful tools and utilities for your homelab environment.
#
# Note: Both mapped and exposed ports are documented. The long-term plan is to reduce direct port exposure in favor of reverse proxying for internal services.
#
# Required environment variables:
# - DOCKER_DATA_BASEFOLDER: Base directory for persistent data
# - DOCKER_MEDIA_BASEFOLDER: Base directory for media files
#
# Optional environment variables:
# - TELEGRAM_API_ID: Telegram API ID for telegram-files
# - TELEGRAM_API_HASH: Telegram API hash for telegram-files

services:
  convertx:
    image: ghcr.io/c4illin/convertx
    container_name: convertx
    restart: always
    ports:
      - 3003:3000 # Web UI (external mapping)
    expose:
      - 3000 # Web UI (internal, for reverse proxy or internal access)
    environment:
      - ACCOUNT_REGISTRATION=false
      - HTTP_ALLOWED=true
      - ALLOW_UNAUTHENTICATED=false
      - AUTO_DELETE_EVERY_N_HOURS=24
    volumes:
      - ${DOCKER_DATA_BASEFOLDER:-/opt/docker/data}/convertx:/app/data

  cup:
    image: ghcr.io/sergi0g/cup:latest
    container_name: cup
    restart: unless-stopped
    command: serve
    ports:
      - 8004:8000 # Web UI (external mapping)
    expose:
      - 8000 # Web UI (internal, for reverse proxy or internal access)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - tools_network

  filebrowser:
    image: filebrowser/filebrowser:s6
    container_name: filebrowser
    restart: always
    ports:
      - 8085:80 # Web UI (external mapping)
    expose:
      - 80 # Web UI (internal, for reverse proxy or internal access)
    environment:
      - PGID=1000
      - PUID=1000
    volumes:
      - ${DOCKER_DATA_BASEFOLDER:-/opt/docker/data}/test:/srv
      - ${DOCKER_DATA_BASEFOLDER:-/opt/docker/data}/filebrowser/filebrowser.db:/database/filebrowser.db
    networks:
      - tools_network

  scrutiny:
    image: ghcr.io/analogj/scrutiny:master-omnibus
    container_name: scrutiny
    restart: always
    ports:
      - 8083:8080 # Web UI (external mapping)
      - 8086:8086 # InfluxDB (external mapping)
    expose:
      - 8080 # Web UI (internal, for reverse proxy or internal access)
      - 8086 # InfluxDB (internal, for reverse proxy or internal access)
    cap_add:
      - SYS_RAWIO
    devices:
      - /dev/sda
    stdin_open: true
    tty: true
    volumes:
      - ${DOCKER_DATA_BASEFOLDER:-/opt/docker/data}/scrutiny/config:/opt/scrutiny/config
      - ${DOCKER_DATA_BASEFOLDER:-/opt/docker/data}/scrutiny/influxdb2:/opt/scrutiny/influxdb
      - /run/udev:/run/udev:ro
    networks:
      - tools_network

  speedtest-tracker:
    image: linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker
    restart: always
    ports:
      - 8084:80 # Web UI (external mapping)
    expose:
      - 80 # Web UI (internal, for reverse proxy or internal access)
    environment:
      - PUID=1000
      - PGID=1000
      - DB_CONNECTION=sqlite
      - APP_KEY=base64:xz6aCq7elg5Di1WCbBfCGdnXjtf9wQV3Ly3tERwQaGI=
      - APP_TIMEZONE=Europe/Rome
      - DISPLAY_TIMEZONE=Europe/Rome
      - SPEEDTEST_SCHEDULE=*/30 * * * *
      - PRUNE_RESULTS_OLDER_THAN=0
    volumes:
      - ${DOCKER_DATA_BASEFOLDER:-/opt/docker/data}/speedtest-tracker:/config
    networks:
      - tools_network

  stirling-pdf:
    image: stirlingtools/stirling-pdf:latest
    container_name: stirling-pdf
    restart: always
    ports:
      - 8082:8080 # Web UI (external mapping)
    expose:
      - 8080 # Web UI (internal, for reverse proxy or internal access)
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
      - LANGS=en_GB
    volumes:
      - ${DOCKER_DATA_BASEFOLDER:-/opt/docker/data}/stirling-pdf/tessdata:/usr/share/tessdata
      - ${DOCKER_DATA_BASEFOLDER:-/opt/docker/data}/stirling-pdf/configs:/configs
      - ${DOCKER_DATA_BASEFOLDER:-/opt/docker/data}/stirling-pdf/customFiles:/customFiles
      - ${DOCKER_DATA_BASEFOLDER:-/opt/docker/data}/stirling-pdf/logs:/logs
      - ${DOCKER_DATA_BASEFOLDER:-/opt/docker/data}/stirling-pdf/pipeline:/pipeline
    networks:
      - tools_network

  telegram-files:
    image: ghcr.io/jarvis2f/telegram-files:latest
    container_name: telegram-files
    restart: always
    ports:
      - 6543:80 # Web UI (external mapping)
    expose:
      - 80 # Web UI (internal, for reverse proxy or internal access)
    environment:
      - APP_ENV=prod
      - APP_ROOT=/app/data
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
    volumes:
      - ${DOCKER_DATA_BASEFOLDER:-/opt/docker/data}/tg-files:/app/data
      - ${DOCKER_MEDIA_BASEFOLDER:-/opt/docker/media}/telegram:/media
    networks:
      - tools_network

  upsnap:
    image: ghcr.io/seriousm4x/upsnap:latest
    container_name: upsnap
    restart: always
    network_mode: host
    expose:
      - 5001 # Web UI (exposed via host networking, for reverse proxy or internal access)
    environment:
      - TZ=Europe/Rome
      - UPSNAP_INTERVAL=@every 10s
      - UPSNAP_SCAN_RANGE=192.168.0.0/24
      - UPSNAP_WEBSITE_TITLE=UpSnap
    volumes:
      - ${DOCKER_DATA_BASEFOLDER:-/opt/docker/data}/upsnap/data:/app/pb_data
    entrypoint: /bin/sh -c "./upsnap serve --http 0.0.0.0:5001"
    # Note: UpSnap uses host networking, so port 5001 is exposed directly on the host.

networks:
  tools_network:
    name: tools_network
    driver: bridge
