version: '3.3'
services:
  stirling-pdf:
    container_name: stirling-pdf
    #different tags explaination -> https://github.com/Stirling-Tools/Stirling-PDF/blob/main/Version-groups.md
    image: frooodle/s-pdf:latest 
    # image: frooodle/s-pdf:latest-ultra-lite
    ports:
      - '8082:8080'
    volumes:
      - ${DOCKER_DATA_BASEFOLDER}/stirling-pdf/tessdata:/usr/share/tessdata #Required for extra OCR languages
      - ${DOCKER_DATA_BASEFOLDER}/stirling-pdf/configs:/configs
#      - /location/of/customFiles:/customFiles/
#      - /location/of/logs:/logs/
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
      - LANGS=en_GB

  speedtest-tracker:
    container_name: speedtest-tracker
    ports:
        - 8084:80
       # - 8443:443
    environment:
        - PUID=1000
        - PGID=1000
        - DB_CONNECTION=sqlite
    volumes:
        - ${DOCKER_DATA_BASEFOLDER}/speedtest-tracker:/config
       # - /path/to-custom-ssl-keys:/config/keys
    image: lscr.io/linuxserver/speedtest-tracker:latest
    restart: unless-stopped