# this file contains a few env variables that you have to manually set in portainer or replace before deploy with the actual text
# - ${DOCKER_DATA_BASEFOLDER}
# - ${DOCKER_MEDIA_BASEFOLDER}
# - ${PASSWORD}
# - ${USERNAME}

services:
  transmission:
    image: linuxserver/transmission:4.0.6-r0-ls248

    #image: linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - USER=${USERNAME}
      - PASS=${PASSWORD}
      - DOCKER_MODS=linuxserver/mods:transmission-floodui
    volumes:
      - ${DOCKER_DATA_BASEFOLDER}/transmission/config:/config
      - ${DOCKER_DATA_BASEFOLDER}/transmission/watch:/watch
      - ${DOCKER_MEDIA_BASEFOLDER}/downloads:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: always
