# Nginx Proxy Manager Stack
# This stack provides a reverse proxy solution with optional mTLS support.
#
# Note: Both mapped and exposed ports are documented. The long-term plan is to reduce direct port exposure in favor of reverse proxying for internal services.
#
# Required environment variables:
# - DOCKER_DATA_BASEFOLDER: Base directory for persistent data
# - YOUR_DOMAIN: your domain name (e.g., your-domain.duckdns.org)
# - TINYAUTH_SECRET: Secret key for TinyAuth
# - POCKET_ID_CLIENT_ID: Client ID for Pocket ID integration
# - POCKET_ID_CLIENT_SECRET: Client Secret for Pocket ID integration
#
# Optional environment variables (for mTLS):
# - STEP_CA_NAME: Name of your Certificate Authority
# - STEP_CA_DNS_NAMES: DNS names for your CA
# - STEP_CA_PASSWORD: Password for your CA

services:
  app:
    container_name: nginx-proxy-manager
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - 80:80 # Public HTTP Port (external mapping)
      - 443:443 # Public HTTPS Port (external mapping)
      - 83:81 # Admin Web Port (external mapping)
    expose:
      - 80 # Internal HTTP port for reverse proxy or internal access
      - 443 # Internal HTTPS port for reverse proxy or internal access
      - 81 # Internal Admin Web port for reverse proxy or internal access
    environment:
      DISABLE_IPV6: true
      PUID: 1000
      PGID: 1000
    volumes:
      - ${DOCKER_DATA_BASEFOLDER:-/opt/docker/data}/NPM/data:/data
      - ${DOCKER_DATA_BASEFOLDER:-/opt/docker/data}/NPM/letsencrypt:/etc/letsencrypt
      - ${DOCKER_DATA_BASEFOLDER:-/opt/docker/data}/step/certs/root_ca.crt:/etc/nginx/ssl/homelab/root_ca.crt:ro
    networks:
      - npm_network

  tinyauth:
    container_name: tinyauth
    image: ghcr.io/steveiliop56/tinyauth:v3
    restart: unless-stopped
    environment:
      # https://tinyauth.app/docs/getting-started.html
      - SECRET=${TINYAUTH_SECRET} # openssl rand -base64 32 | tr -dc 'a-zA-Z0-9' | head -c 32
      - APP_URL=https://tinyauth.${YOUR_DOMAIN:-example.com}
      #- USERS=user:$$2a$$10$$UdLYoJ5lgPsC0RKqYH/jMua7zIn0g9kPqWmhYayJYLaZQ/FTmH2/u # user:password

      #Pocket ID configuration from: https://tinyauth.app/docs/guides/pocket-id
      - GENERIC_CLIENT_ID=${POCKET_ID_CLIENT_ID}
      - GENERIC_CLIENT_SECRET=${POCKET_ID_CLIENT_SECRET}
      - GENERIC_AUTH_URL=https://pocket-id.${YOUR_DOMAIN:-example.com}/authorize
      - GENERIC_TOKEN_URL=https://pocket-id.${YOUR_DOMAIN:-example.com}/api/oidc/token
      - GENERIC_USER_URL=https://pocket-id.${YOUR_DOMAIN:-example.com}/api/oidc/userinfo
      - GENERIC_SCOPES=openid email profile groups
      - GENERIC_NAME=Pocket ID
    networks:
      - npm_network

  step-ca:
    container_name: step-ca
    image: smallstep/step-ca
    restart: unless-stopped
    ports:
      - 9001:9000 # Step CA API (external mapping)
    expose:
      - 9000 # Internal Step CA API port for reverse proxy or internal access
    volumes:
      - ${DOCKER_DATA_BASEFOLDER:-/opt/docker/data}/step:/home/step
    environment:
      DOCKER_STEPCA_INIT_NAME: ${STEP_CA_NAME}
      DOCKER_STEPCA_INIT_DNS_NAMES: ${STEP_CA_DNS_NAMES}
      DOCKER_STEPCA_INIT_PASSWORD: ${STEP_CA_PASSWORD}
    networks:
      - npm_network

networks:
  npm_network:
    name: npm_network
    driver: bridge
